### PR TITLE
Fill AgentAuth during Runtime creation

### LINKED ISSUE #90: AgentAuth is not populated when creating Runtime
When I execute the following query:
```
mutation {
  result: createRuntime(
    in: { name: "runtime-1", description: "runtime-1-description" }
  ) {
    id
    name
    description

    agentAuth {
      credential {
        ... on BasicCredentialData {
          username
          password
        }
        ... on OAuthCredentialData {
          clientId
          clientSecret
          url
        }
      }
    }
  }
}

```

I got the following error:
```
{
  "errors": [
    {
      "message": "must not be null",
      "path": [
        "result",
        "agentAuth"
      ]
    }
  ],
  "data": null
}
```
Additionally, I do not see any errors in the director logs which is strange because of this is a server side error.

### PR DESCRIPTION
**Pull request by pkosiec**
**Description**

Changes proposed in this pull request:

- Fill AgentAuth during Runtime creation

**Related issue(s)**
Resolves #90

### CODE REVIEW

File: components/director/internal/model/runtime.go [hunk 1]
```diff
@@ -103,13 +103,22 @@ type RuntimeInput struct {
...
+
 	return &Runtime{
 		ID:          id,
 		Name:        i.Name,
 		Description: i.Description,
 		Tenant:      tenant,
 		Labels:      i.Labels,
 		Annotations: i.Annotations,
+		AgentAuth: &Auth{},
+		Status: &RuntimeStatus{
```
Comment (aszecowka) [inline components/director/internal/model/runtime.go]: move it to service

File: components/director/internal/model/runtime.go [hunk 2]
```diff
@@ -103,13 +103,22 @@ type RuntimeInput struct {
...
+			Condition: RuntimeStatusConditionInitial,
+			Timestamp: time.Now(),
```
Comment (aszecowka) [inline components/director/internal/model/runtime.go]: don't use `time.Now()` because it cannot be tested, introduce TImeProvider interface

File: components/director/internal/model/runtime_test.go [hunk 3]
```diff
@@ -274,3 +275,65 @@ func TestRuntime_DeleteAnnotation(t *testing.T) {
...
+		},
+		{
+			Name:     "Nil",
+			Input:    nil,
+			Expected: nil,
+		},
+	}
+
+	for i, testCase := range testCases {
+		t.Run(fmt.Sprintf("%d: %s", i, testCase.Name), func(t *testing.T) {
```
Comment (aszecowka) [inline components/director/internal/model/runtime_test.go]: what value gives you this index in the name of the test????????????
